name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.MY }}
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: bash
        
        run: |
             echo  $env_var
      
